config/routes.rb
Rails.application.routes.draw do
  root 'notes#index'

  resources :notes, only: [:index, :show] do
    resources :comments, only: [:create]
  end

  namespace :admin do
    resources :notes
    resources :sessions

    get 'login' => 'sessions#new'
    post 'login' => 'sessions#create'
    get 'logout' => 'sessions#destroy'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
  has_secure_password

  validates :email, presence: true, format: { with: URI::MailTo::EMAIL_REGEXP }
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :commenter, :email, :content, presence: true
  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP }
end

app/models/note.rb
class Note < ApplicationRecord
  has_rich_text :content

  has_many :comments, dependent: :destroy

  validates :title, :content, presence: true
  validates :title, uniqueness: true
end

app/controllers/admin/base_controller.rb
module Admin
  class BaseController < ApplicationController
    before_action :authenticate_author!

    private

    def authenticate_author!
      if signed_in?
        @author ||= Author.find(session[:author_id])
      else
        redirect_to root_path
      end
    end

    def signed_in?
      session[:author_id].present?
    end
  end
end

app/controllers/admin/notes_controller.rb
module Admin
  class NotesController < BaseController
    before_action :set_note, only: [:show, :edit, :update, :destroy]

    def index
      @notes = Note.all
    end

    def new
      @note = Note.new
    end

    def show
    end

    def create
      @note = Note.new(note_params)
      if @note.save
        redirect_to [:admin, @note], notice: '新建成功！'
      else
        flash[:notice] = @note.errors.full_messages[0]
        render :new
      end
    end

    def edit
    end

    def update
      if @note.update(note_params)
        redirect_to [:admin, @note], notice: '更新成功！'
      else
        render :edit
      end
    end

    def destroy
      @note.destroy
      redirect_to admin_notes_url, notice: '删除成功！'
    end

    private

    def set_note
      @note = Note.find(params[:id])
    end

    def note_params
      params.require(:note).permit(:title, :content)
    end
  end
end

app/controllers/admin/sessions_controller.rb
module Admin
  class SessionsController < BaseController
    skip_before_action :authenticate_author!, only: [:new, :create]

    def new
    end

    def create
      author = Author.find_by(email: params[:email])
      if author&.authenticate(params[:password])
        session[:author_id] = author.id
        flash[:success] = 'Successfully logged in !'
        redirect_to admin_notes_url
      else
        flash[:notice] = 'Invalid email or password'
        redirect_to [:admin, :login]
      end
    end

    def destroy
      reset_session
      flash[:notice] = 'Successfully logged out !'
      redirect_to [:admin, :login]
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @note = Note.find(params[:note_id])
    @comment = @note.comments.create(comment_params)
    redirect_to note_path(@note)
  end

  private

  def comment_params
    params.require(:comment).permit(:commenter, :email, :content)
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  def index
    @notes = Note.all
  end

  def show
    @note = Note.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/admin/notes/_form.html.erb
<%= form_with(model: [:admin, note], local: true) do |form| %>
  <% if note.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(note.errors.count, "error") %> prohibited this note from being saved:</h2>

      <ul>
        <% note.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>
  <p>
    <%= form.label :content %><br>
    <%= form.rich_text_area :content %>
  </p>
  <%= form.submit %>
<% end %>

app/views/admin/notes/edit.html.erb
<% title = @note.title %>
<% content_for :title do %>
  <% title %>
<% end %>
<h1><%= title %></h1>

<%= render 'form', note: @note %>

<br>
<%= link_to '返回', admin_notes_path %>

app/views/admin/notes/index.html.erb
<% title = '笔记列表' %>
<% content_for :title do %>
  <% title %>
<% end %>

<h1><%= title %></h1>

<%= link_to '新建笔记', new_admin_note_path %>

<table>
  <thead>
  <tr>
    <th>标题</th>
    <th colspan="2"></th>
  </tr>
  </thead>

  <tbody>
  <% @notes.each do |note| %>
    <tr>
      <td><%= link_to note.title, [:admin, note] %></td>
      <td><%= link_to '编辑', edit_admin_note_path(note) %></td>
      <td><%= link_to '删除', [:admin, note], method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/admin/notes/new.html.erb
<p id="notice"><%= notice %></p>

<% title = '新建笔记' %>
<% content_for :title do %>
  <% title %>
<% end %>
<h1><%= title %></h1>

<%= form_for [:admin, @note] do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>
  <%= f.submit '新建' %>
<% end %>

<br>
<%= link_to '返回', admin_notes_path %>

app/views/admin/notes/show.html.erb
<% title = @note.title %>
<% content_for :title do %>
  <% title %>
<% end %>

<%= link_to '返回', admin_notes_path %>

<h1><%= title %></h1>

<article>
  <%= @note.content %>
</article>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %></title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= favicon_link_tag %>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<main class="container">
  <p id="notice"><%= notice %></p>

  <%= yield %>
</main>
</body>
</html>

app/views/notes/index.html.erb
<% content_for :title do %>
  Note
<% end %>

<ul>
  <% @notes.each do |note| %>
    <li><%= link_to note.title, note %></li>
  <% end %>
</ul>

app/views/notes/show.html.erb
<% title = @note.title %>

<% content_for :title do %>
  <%= title %>
<% end %>

<h1><%= title %></h1>

<article>
  <%= @note.content %>
</article>

<hr>

<h2>评论</h2>
<% @note.comments.each do |comment| %>
  <strong><%= comment.commenter %>：</strong>
  <p><%= comment.content %></p>
<% end %>

<hr>

<h2>发表评论：</h2>
<%= form_with(model: [@note, @note.comments.build], local: true) do |form| %>
  <div>
    <%= form.label :content, '评论' %>
    <%= form.text_area :content, required: true %>
  </div>
  <div>
    <%= form.label :commenter, '姓名' %>
    <%= form.text_field :commenter, required: true %>
  </div>
  <div>
    <%= form.label :email, '电子邮箱' %>
    <%= form.email_field :email, required: true %>
  </div>
  <%= form.submit '发表', class: 'button-primary' %>
<% end %>

<script>
  (function () {
    const rememberInputs = [
      {selector: '#comment_commenter', key: 'commenter'},
      {selector: '#comment_email', key: 'email'}
    ]

    const prefixKey = 'note_comment_'

    rememberInputs.forEach(rememberInput => {
      const input = document.querySelector(rememberInput.selector)
      const key = prefixKey + rememberInput.key
      input.onblur = function () {
        localStorage.setItem(key, input.value)
      }
      input.value = localStorage.getItem(key)
    })
  })()
</script>